services:
  # CockroachDB!!
  db:
    image: cockroachdb/cockroach:v25.2.5
    command: start-single-node --insecure
    env_file:
      - .env
    ports:
      - "26258:26257"  # SQL port
      - "8081:8080"    # Admin UI
    volumes:
      - cockroach_data:/cockroach/cockroach-data

  # REDIS!!
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Phoenix!!
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIX_ENV: prod
    env_file:
      - .env.prod
    ports:
      - "4000:4000"  # Phoenix web interface
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:rw
      - /app/deps
      - /app/_build
    command: /usr/local/bin/start.sh
    restart: unless-stopped

  # Fake Email Service!!
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  cockroach_data:
  redis_data:
