services:
  db:
    image: cockroachdb/cockroach:v25.2.5
    command: start-single-node --insecure
    env_file:
      - .env.prod
    ports:
      - "26258:26257"  # SQL port
      - "8081:8080"    # Admin UI
    volumes:
      - cockroach_data_prod:/cockroach/cockroach-data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data

  web:
    build:
      context: .
      args:
        MIX_ENV: prod
    env_file:
      - .env.prod
    ports:
      - "4000:4000"
    volumes:
      - .:/app:rw
      - /app/priv/static/assets
    depends_on:
      - db
      - redis
    command: /usr/local/bin/start.sh
    volumes: []  # no bind mounts in prod

volumes:
  cockroach_data_prod:
  redis_data_prod: